server:
  port: 9991

commercetools:
   commerce:
     api:
       host:  https://api.europe-west1.gcp.commercetools.com
       auth_url: https://auth.europe-west1.gcp.commercetools.com
       client_id: F0Wy07MV8_JqSw780DE5P_Wg
       client_secret: KGGrhD3vqJhh_iN5pjL4rt0UiRDxEVx0
       project-key: credera-2test-b2b
sap:
  commerce:
    api:
      OAUTH_URI: https://api.canv1f-techaspec2-d1-public.model-t.cc.commerce.ondemand.com/authorizationserver/
      OAUTH_CLIENT_ID: vueStorefront
      OAUTH_CLIENT_SECRET: vueStorefront
      OAUTH_TOKEN_ENDPOINT: /oauth/token
      OAUTH_TOKEN_REVOKE_ENDPOINT: /oauth/revoke
